# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import mailqueue.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0002_mailermessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=mailqueue.utils.upload_to),
        ),
    ]
